-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, P.PRICE*SUM(O.SALES_AMOUNT) AS PRICE
-- P.PRODUCT_ID, SUM(P.PRICE*O.SALES_AMOUNT)AS PRICE
FROM PRODUCT P
LEFT JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.SALES_AMOUNT IS NOT NULL
GROUP BY PRODUCT_CODE
ORDER BY PRICE DESC ,PRODUCT_CODE ASC

